apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.0 (40646f47)
  creationTimestamp: null
  labels:
    io.kompose.service: message-consumer
  name: message-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: message-consumer
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.network/resolute: "true"
        io.kompose.service: message-consumer
    spec:
      containers:
      - name: message-consumer
        image: message-queue-consumer.jar
        env:
            - name: SPRING_DATASOURCE_PASSWORD
              value: postgres
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgresql:5432/postgres
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: spring_rabbitmq_host
              value: rabbitmq
            - name: spring_rabbitmq_port
              value: "5672"
            - name: spring_rabbitmq_password
              value: guest
            - name: spring_rabbitmq_username
              value: guest
        ports:
          - containerPort: 8091
      restartPolicy: Always
status: {}
