---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-pv-1
  labels:
    io.kompose.service: postgres
    type: local
spec:
  storageClassName: manual
#  claimRef:
#    name: postgres-pv-claim
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data"