---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: message-consumer
spec:
  replicas: 1
  selector:
    matchLabels:
      name: message-consumer
  template:
    metadata:
      labels:
        name: message-consumer
    spec:
      containers:
        - name: message-consumer
          env: # Setting Enviornmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf  # name of configMap
                  key: host
            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: postgres-conf
                  key: name
            - name: POSTGRES_USER  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials # Secret Name
                  key: postgres_user
            - name: POSTGRES_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: postgres-credentials
                  key: postgres_password
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: spring_rabbitmq_host
              value: rabbitmq
            - name: spring_rabbitmq_port
              value: "5672"
            - name: spring_rabbitmq_password
              value: guest
            - name: spring_rabbitmq_username
              value: guest
          image: miniocean/message-consumer
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091

---
apiVersion: v1
kind: Service
metadata:
  name: message-consumer
spec:
  ports:
    - port: 8091
      targetPort: 8091
  selector:
    name: message-consumer
  type: LoadBalancer