apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pv-claim
  labels:
    io.kompose.service: postgres
    tier: database
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi