apiVersion: v1
kind: Service
metadata:
  name: postgres
  labels:
    name: postgres
    tier: database
spec:
  type: LoadBalancer
  ports:
    - port: 5432
  selector:
    name: postgres
    tier: database
